# Generated by Django 4.2.24 on 2025-10-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_alter_order_options_alter_orderupdate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='General Inquiry', max_length=200),
        ),
    ]
