# Generated by Django 4.2.24 on 2025-09-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_product_description_product_is_new_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mens', 'Mens'), ('womens', 'Womens'), ('kids', 'Kids '), ('accessories', 'Accessories'), ('newarrivals', 'New Arrivals')], max_length=50),
        ),
    ]
