# Generated by Django 4.2.24 on 2025-09-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mens', 'Mens'), ('womens', 'Womens'), ('kids', 'Kids'), ('accessories', 'Accessories'), ('newarrivals', 'New Arrivals')], max_length=50),
        ),
    ]
